name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore CrudQL/CrudQL.sln
      - name: Build
        run: dotnet build CrudQL/CrudQL.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test CrudQL/CrudQL.sln --configuration Release --no-build --logger "trx"
